name = "JosephsonCircuitsOptimizer"
uuid = "f0ccd376-68f0-4c3f-ac14-a7083ed4f996"
authors = ["emanuele-palumbo <emanuele.palumbo@polito.it>"]
version = "0.2.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GaussianProcesses = "891a1506-143c-57d2-908e-e1f8e92e6de9"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
HDF5_jll = "0234f1f7-429e-5d53-9886-15a909be8d59"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JosephsonCircuits = "23a5dba6-321f-4fcf-be1e-689e290df087"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuasiMonteCarlo = "8a4e6c94-4038-4cdc-81c3-7e6ffdb2a71b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Surrogates = "6fc51010-71bc-11e9-0e15-a3fcc6593c49"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
Colors = "0.13"
DSP = "0.8"
DataFrames = "1.7"
Dates = "1.11"
FileIO = "1.17"
GLMakie = "0.11"
GaussianProcesses = "0.12"
HDF5 = "0.17"
HDF5_jll = "1.14"
Interpolations = "0.15"
JSON = "0.21"
JosephsonCircuits = "0.4"
KernelDensity = "0.6"
LaTeXStrings = "1.4"
LinearAlgebra = "1.11"
Logging = "1.11"
LoggingExtras = "1.2"
Makie = "0.22"
Pkg = "1.11"
Plots = "1.40"
QuasiMonteCarlo = "0.3"
Random = "1.11"
Revise = "3.7"
Statistics = "1.11"
StatsBase = "0.34"
Surrogates = "6.10"
Symbolics = "6.29"
Test = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
